"""Add field_confidences to extractions

Revision ID: 4af2bab1c820
Revises: f38e78df74c3
Create Date: 2025-12-25 02:10:41.461837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4af2bab1c820'
down_revision: Union[str, Sequence[str], None] = 'f38e78df74c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extractions', sa.Column('field_confidences', sa.JSON(), nullable=True, comment='Per-field confidence scores (0.0 to 1.0)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('extractions', 'field_confidences')
    # ### end Alembic commands ###
