"""add_file_content_to_documents

Revision ID: 5aa2801c9ad0
Revises: 4af2bab1c820
Create Date: 2025-12-25 22:04:57.497523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5aa2801c9ad0'
down_revision: Union[str, Sequence[str], None] = '4af2bab1c820'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_content', sa.LargeBinary(), nullable=True, comment='Stored PDF file content for retrieval'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'file_content')
    # ### end Alembic commands ###
